### ISSUE TITLE
Add Custom Exceptions

### ISSUE THREAD

**Issue by LordRekishi** [Patlenlix/CrimeDatabase#11]
Add at least three custom exceptions

**Comment by helenahalldiniths** [comment]
To clarify I made a list of what needs to be done:
- Add a class that can represent an error message.
- Add a couple of custom exceptions (that extends WebApplicationException)
- Add mappers for the exceptions (classes that extends ExceptionMapper)
- Replace/add meaningful exceptions for each HTTP request.

**Comment by helenahalldiniths** [comment]
Här trodde jag lite naivt att det skulle fungera som i Java EE... 
Ovan stämmer inte, jag ska undersöka lite mer vad som gäller i spring.

**Comment by helenahalldiniths** [comment]
I think this is a good resource: https://www.baeldung.com/exception-handling-for-rest-with-spring

**Comment by helenahalldiniths** [comment]
I think both solution 3 and 4 can be a good way to do it (depending on our version of spring) :)

**Comment by FelixJacobsen** [comment]
I think solution 3 is a good and clean way of handling exceptions!
