### ISSUE TITLE
release.yml / tag

### ISSUE THREAD

**Issue by FelixJacobsen** [Patlenlix/CrimeDatabase#24]
To create a release-tag badge we need to set a tag. Not sure if this is done in workflow or in any other config file.

**Comment by helenahalldiniths** [comment]
I didn't have time to start this today, so if anyone wants to do it just go ahead. Otherwise I will give it a go tomorrow.

**Comment by helenahalldiniths** [comment]
I will use this resource, https://docs.docker.com/ci-cd/github-actions/
