### ISSUE TITLE
Setup MySQL database

### ISSUE THREAD

**Issue by FelixJacobsen** [Patlenlix/CrimeDatabase#33]
We are currently using H2 database which is good for testing but later we want to switch to MySQL.

Helena found good information here:
https://spring.io/guides/gs/accessing-data-mysql/

**Comment by helenahalldiniths** [comment]
We can use one database during testing(H2) and one during production (mySQL). 

One option is to create two .properties files in the folder resources, an other option is to use profiles(https://www.baeldung.com/spring-profiles). II'm not exactly sure how either of these work, but it can be done :)

**Comment by helenahalldiniths** [comment]
https://www.baeldung.com/spring-testing-separate-data-source
This might be a good resource

**Comment by LordRekishi** [comment]
Why do we need a separate database for testing and release? Is MySQL troublesome in some way?

**Comment by FelixJacobsen** [comment]
We don't, but setting up H2 is a very simple and quick solution until we have a mySQL database.

**Comment by LordRekishi** [comment]
In order for this to work we'll need to implement [Test Containers](https://www.testcontainers.org/quickstart/junit_5_quickstart/)
