### ISSUE TITLE
Fix Maven Wrapper for Mac users

### ISSUE THREAD

**Issue by LordRekishi** [Patlenlix/CrimeDatabase#56]
Fix mvnw so it works for mac users. The mvnw file is not set with the executable tag in mac file systems.
We need to fix this by running the following git command: `git update-index --chmod=+x mvnw`

**Comment by FelixJacobsen** [comment]
![macmeme](https://user-images.githubusercontent.com/89127725/158205197-42388dcf-5d9d-4a4f-a1f3-b3e8849e05a7.jpg)

**Comment by LordRekishi** [comment]
Alternative solution: Get a real computer? :D
