### ISSUE TITLE
Implement JMS

### ISSUE THREAD

**Issue by LordRekishi** [Patlenlix/CrimeDatabase#63]
Implement Java Messaging System or similar.
Use either ActiveMQ or RabbitMQ.

**Comment by helenahalldiniths** [comment]
Ojsan, råkade lägga till mig själv... Men nu är det rätt gubbe på jobbet!

**Comment by LordRekishi** [comment]
Planning to use RabbitMQ istead of ActiveMQ
https://hub.docker.com/_/rabbitmq
