### ISSUE TITLE
Enable Dependabot 

### ISSUE THREAD

**Issue by LordRekishi** [Patlenlix/CrimeDatabase#9]
Enable checking maven and dependencies

**Comment by helenahalldiniths** [comment]
I have been thinking about what Martin mentioned yesterday (that we do not need to set any version numbers for our dependencies since the parent provides it). Maybe a dependabot is unnessesary?

**Comment by FelixJacobsen** [comment]
A problem that might occur is that a dependency has a vulnerability / security risk, In that case I think dependabot would provide us with a varning.

But we maybe should focus our attention on more important matters?

**Comment by helenahalldiniths** [comment]
That is true! 

Might not be a hight priority at the moment, we can look at it later on if we have the time.

**Comment by LordRekishi** [comment]
Moving this issue to Week 12
